alias ..="cd .."
alias cd..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias g='git'
alias gaa='g aa'
alias gc='g c'
alias gcmm='g cmm'
alias gd='g d'
alias gds='g ds'
alias gf='g f'
alias gl='g l'
alias gs='g s'
alias fireup='git pull && npm install && npm start'
alias go='npm start'
alias n='npm'
alias ng='npm -g'
