alias ..="cd .."
alias cd..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias l="ls -lah"

alias g='git'
alias gaa='g aa'
alias gap='g ap'
alias gau='g au'
alias gc='g c'
alias gcmm='g cmm'
alias gd='g d'
alias gds='g ds'
alias gdw='g dw'
alias gf='g f'
alias gl='g l'
alias gll='g ll'
alias gla='g la'
alias gp='g p'
alias gr='g r'
alias gs='g s'
alias gup='g up'
alias fireup='git pull && npm install && npm start'
alias go='npm start'
alias build='npm run build'
alias n='npm'
alias ng='npm -g'
